packages:
  - packages/core
  - packages/i18next
  - packages/paraglide
  - packages/formatjs
  - packages/cli

catalog:
  '@typescript-eslint/scope-manager': ^8.63.0
  oxc-parser: ^0.139.0
  oxc-resolver: ^11.23.0

savePrefix: ''
engineStrict: true
pmOnFail: error
strictPeerDependencies: true
minimumReleaseAge: 4320
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 43200
blockExoticSubdeps: true
ignoreScripts: true
strictDepBuilds: true
sideEffectsCache: false
enablePrePostScripts: false

allowBuilds:
  esbuild: true
